#RosalindProblem3.py

s = 'GAGAACTAGGACAACCGAAGACTCTAGCACCGTGGGTTATAAAGAACAATCCCACCAAGACACTACGGATCACAGGGAGGTCTCATTTGGAGTACGATCTCCAGGGAAGCGTCGCCCGAAGTGCCTTACTGTCCTATCCGGGAATTCCGCAATAGCAGCTGCCGCCCCTGGTCCAGCGTCCCTTCTGGTGCGACGCTCGATGTCCGCCTATCATTTCCTCCACTCCGGGTGGCAGTGCCAACTAGTAAGTGCTTCCTTTTTCAGAGAGACGCCAGCACGCGTACAGAAAAAGAGATTTGCGAGTAATACAGTCCTGTGAAGGGGTCCCACACACGTCTTTGACACCCGATCCCAATTTCAGGCTGGCGTAGAAGGACGATACACGTCGCAGGACACCCCCAACAGTATTCCTAGCCCCCTTACCGGGTTAGGAAGGGATCGAGCCATGGTCGCGCTCCTTCTCGGACGAGTCTCACAAACTTACGACAAGGGTTGAATTTTCCCCAAGAACGTTCGAGAGGATTTTAAGGGGCCTAACATCCATGACTGAGTGATTCGCCGTTGGACCCCCATTGCTAGGGTCGACGAGGGAACGGGGGTTCTAGCCTGGCGCACCACAATTGGTCATGAGCTCCTCCGGGGCCAGAATAGGCCGTCCTTGACGGCCCCTCGACTGGCGTTATTAGGGATGTCTATTCAACCTAGCGTTCTGCATTCATGTATGAGGGGGTCCAGTGTCCACGGCTGTCCGACACGCGGACTAATTGCGGCGTAGAAGGTCGGGGGGCTGTATTGTTGCCGTTGGTGTATGTTACAATGGCATCGCTGCGAAATTTTGACCGGCCTTGTTGGAGCCCTCAGCGGTTCACGACCACATTTCGGAGTGCATTCTTTTAAGTGCCCCGACTACACGTGTTGGGCGACTAGGTATGTATATTCTAAGACCGTAACAAAGTATGATCTTGGGTCA'

#Given: A DNA string s of length at most 1000 bp.
#Return: The reverse complement of s.

file = open('RosalindProblem3.txt','w') 

revComp = ''

def getComplement(sense):
	if sense == 'A':
		return 'T'
	elif sense == 'T':
		return 'A'
	elif sense == 'G':
		return 'C'
	elif sense == 'C':
		return 'G'
	else:
		print('There was an error! Invalid input sequence.')
		return '?'

for i in range(len(s)):
	revComp += getComplement(s[len(s)-i-1])

file.write(revComp)

file.close()